<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/css/style.css">
</head>
<body>
<div class="row">
    <div class="col-sm-2 col-md-3 col-lg-3"></div>
    <div class="col-sm-8 col-md-6 col-lg-6">
    <?php if (!empty($errors) || !empty($warning) || !empty($success) || !empty($info)): ?>
    <div class="messages">
        <?php if (!empty($errors)): ?>
            <?php foreach ($errors as $error): ?>
            <div class="alert alert-danger"><?= $error ?></div>
            <?php endforeach; ?>
        <?php endif; ?>
        <?php if (!empty($warning)): ?>
            <?php foreach ($warning as $warning_o): ?>
            <div class="alert alert-warning"><?= $warning_o ?></div>
            <?php endforeach; ?>
        <?php endif; ?>
        <?php if (!empty($success)): ?>
            <?php foreach ($success as $success_o): ?>
            <div class="alert alert-success"><?= $success_o ?></div>
            <?php endforeach; ?>
        <?php endif; ?>
        <?php if (!empty($info)): ?>
            <?php foreach ($info as $info_o): ?>
            <div class="alert alert-success"><?= $info_o ?></div>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>
    <?php endif; ?>
    <form action="/login" method="post">
        <input type="hidden" name="token" value="<?= $token ?>">
        <label>
            Username:
            <input type="text" name="username" value="" placeholder="Username">
        </label>
        <label>
            Password:
            <input type="password" name="password" value="" placeholder="password">
        </label>
        <input type="submit" name="login" value="Login">
    </form>
    </div>
    <div class="col-sm-2 col-md-3 col-lg-3"></div>
</div>
</body>
</html>