<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Installation start</title>
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/css/style.css">
</head>
<body>
<div class="row">
    <div class="col-sm-2 col-md-3 col-lg-3"></div>
    <div class="col-sm-8 col-md-6 col-lg-6">
    <form action="/install" method="post">
        <input type="hidden" name="token" value="<?= $token ?>">
        First user:<br>
        <label>
            Username:
            <input type="text" name="username" value="" placeholder="Username">
        </label><br>
        <label>
            Password:
            <input type="password" name="password" value="" placeholder="Password">
        </label><br>
        <label>
            E-mail:
            <input type="email" name="email" value="" placeholder="E-mail">
        </label><br>
        <input type="submit" name="install" value="Install">
    </form>
    </div>
    <div class="col-sm-2 col-md-3 col-lg-3"></div>
</div>
</body>
</html>