<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User edit</title>
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/css/style.css">
</head>
<body>
<div class="row">
    <div class="col-sm-2 col-md-3 col-lg-3"></div>
    <div class="col-sm-8 col-md-6 col-lg-6">
        <?php if (!empty($_SESSION['id'])): ?>
            <div class="links">
                <ul class="nav nav-pills">
                    <li><a href="/">Posts</a></li>
                    <li><a href="/users">Users</a></li>
                    <li><a href="/user/add">New User</a></li>
                    <li><a href="/logout">Logout</a></li>
                </ul>
            </div>
        <?php endif; ?>
      <?php if (!empty($errors) || !empty($warning) || !empty($success) || !empty($info)): ?>
        <div class="messages">
          <?php if (!empty($errors)): ?>
            <?php foreach ($errors as $error): ?>
              <div class="alert alert-danger"><?= $error ?></div>
            <?php endforeach; ?>
          <?php endif; ?>
          <?php if (!empty($warning)): ?>
            <?php foreach ($warning as $warning_o): ?>
              <div class="alert alert-warning"><?= $warning_o ?></div>
            <?php endforeach; ?>
          <?php endif; ?>
          <?php if (!empty($success)): ?>
            <?php foreach ($success as $success_o): ?>
              <div class="alert alert-success"><?= $success_o ?></div>
            <?php endforeach; ?>
          <?php endif; ?>
          <?php if (!empty($info)): ?>
            <?php foreach ($info as $info_o): ?>
              <div class="alert alert-success"><?= $info_o ?></div>
            <?php endforeach; ?>
          <?php endif; ?>
        </div>
      <?php endif; ?>
        <form action="/user/<?= $is_new ? 'add' : $id . '/edit' ?>" method="post">
            <input type="hidden" name="token" value="<?= $token ?>">
            <label>
                Username:
                <input type="text" name="username" value="<?= $username ?>" placeholder="Username">
            </label><br>
            <?php if ($is_new): ?>
                <label>
                    Password:
                    <input type="password" name="password" value="<?= $password ?>" placeholder="password">
                </label><br>
            <?php endif; ?>
            <label>
                E-mail:
                <input type="email" name="email" value="<?= $email ?>" placeholder="E-mail">
            </label><br>
            <?php if ($is_new): ?>
                <input type="submit" name="create" value="Create">
            <?php else: ?>
                <input type="submit" name="modify" value="Modify">
            <?php endif; ?>
        </form>
    </div>
    <div class="col-sm-2 col-md-3 col-lg-3"></div>
</div>
</body>
</html>